import { MarineObservation, GeofenceCheckResult, PFZAdvisoryResult } from '../types/domain';

export interface RuleBasedData {
  conditions?: MarineObservation;
  geofence?: GeofenceCheckResult;
  pfz?: PFZAdvisoryResult;
  route?: any;
  hazards?: any[];
  vesselData?: any;
  regionalWarnings?: any[];
  inlandData?: {
    name: string;
    state: string;
    type: string;
    nearestPorts: Array<{ name: string; distanceKm: number; sector: string }>;
    context: string;
  };
  conversational?: {
    isGreeting?: boolean;
    capabilities?: string[];
  };
  conceptQuery?: {
    topic: string;
    category?: string;
  };
  safetyAssessment?: any;
  userPrompt?: string;
}

/**
 * Deterministic rule-based explanation engine.
 * Guaranteed zero-hallucination fallback that converts verified observations and domain queries into
 * clear, conversational, professional maritime intelligence answers if all LLM APIs are unreachable.
 */
export function generateRuleBasedResponse(
  intent: string,
  data: RuleBasedData
): string {
  // 1. Inland Territory Inquiries
  if (data.inlandData) {
    const inland = data.inlandData;
    const portBullets = inland.nearestPorts
      .map(
        (p) =>
          `• **${p.name}** (~${p.distanceKm} km away in the ${p.sector})`
      )
      .join('\n');

    return (
      `**${inland.name}** is an inland location in ${inland.state} and does not have direct coastal sea or marine telemetry. ${inland.context}\n\n` +
      `AUREXO / ORCA is dedicated to monitoring India's **7,516 km coastline**, Exclusive Economic Zone (EEZ), and surrounding waters (Arabian Sea, Bay of Bengal, and Indian Ocean).\n\n` +
      `**Major Maritime Trade Gateways for this region:**\n${portBullets}\n\n` +
      `You can click on any coastal point or port (such as Kandla, Mumbai JNPT, Cochin, or Chennai) to inspect live wave heights, wind, SST, and boundary geofences.`
    );
  }

  // 2. Conversational Greetings & Capabilities
  if (data.conversational) {
    return (
      `Hello! I am **AUREXO / ORCA**, an ISRO-standard maritime intelligence copilot for the Indian Ocean, Arabian Sea, and Bay of Bengal.\n\n` +
      `I provide real-time, verified oceanographic and tactical intelligence, including:\n` +
      `• **Live Ocean Telemetry**: Wave heights, swell periods, surface currents, and sea surface temperature (SST).\n` +
      `• **Maritime Weather & Squall Warnings**: Beaufort wind scale, wind gusts, and coastal storm advisories.\n` +
      `• **Geospatial Boundary Sentinel**: Real-time proximity to Pakistan & Sri Lanka IMBL, EEZ limits, and Marine Protected Areas.\n` +
      `• **AIS Fleet Tracking**: Live positions of Indian Coast Guard vessels (like ICGS Samarth), research ships (RV Sagar Kanya), and commercial fleets.\n` +
      `• **Potential Fishing Zones (PFZ)**: INCOIS habitat suitability and thermal front detections.\n` +
      `• **Navigational Corridors**: Great-Circle safe passage routing and transit time calculation.\n\n` +
      `You can click anywhere on the coastal map or ask a direct query in English or any Indian regional language.`
    );
  }

  // 3. Domain Concept Knowledge
  if (data.conceptQuery) {
    const topic = data.conceptQuery.topic.toLowerCase();
    if (topic.includes('kallakkadal') || topic.includes('swell surge')) {
      return (
        `**Kallakkadal (Swell Surge Phenomenon)**:\n\n` +
        `"Kallakkadal" (a Malayalam term formally adopted by UNESCO/WMO) refers to sudden, destructive coastal flooding and high-energy swell surges that occur without any local wind or atmospheric disturbances.\n\n` +
        `• **Origin**: Generated by distant meteorological storms and high-latitude winds in the Southern Ocean (40°S–60°S), thousands of kilometers away.\n` +
        `• **Mechanism**: Long-period swells (15–22 seconds) travel north across the entire Indian Ocean and surge upon reaching shallow coastal waters, causing severe coastal inundation along Kerala, Tamil Nadu, and Lakshadweep.\n` +
        `• **Surveillance**: AUREXO / ORCA tracks swell wave periods in real time using satellite altimetry and oceanographic wave models to detect early swell signatures.`
      );
    }
    if (topic.includes('upwelling') || topic.includes('sst') || topic.includes('temperature')) {
      return (
        `**Coastal Upwelling & Sea Surface Temperature (SST)**:\n\n` +
        `Coastal upwelling is an oceanographic process where offshore winds and Coriolis forces push warm surface water seaward, allowing colder, nutrient-dense deep water to rise to the surface.\n\n` +
        `• **Significance**: Creates pronounced thermal fronts and fuels phytoplankton growth (measured via Chlorophyll-A), forming prime Potential Fishing Zones (PFZ) for pelagic species such as tuna, mackerel, and sardines.\n` +
        `• **Monitoring**: AUREXO / ORCA fuses high-resolution GHRSST satellite observations with Open-Meteo marine telemetry to pinpoint thermal boundaries.`
      );
    }
    if (topic.includes('imbl') || topic.includes('border') || topic.includes('eez')) {
      return (
        `**Maritime Boundaries: IMBL & EEZ**:\n\n` +
        `• **International Maritime Boundary Line (IMBL)**: Delimited bilateral maritime border between neighboring sovereign nations (such as India–Pakistan in the Arabian Sea off Sir Creek/Kutch, and India–Sri Lanka across Palk Bay and Gulf of Mannar).\n` +
        `• **Exclusive Economic Zone (EEZ)**: Extending 200 nautical miles (~370.4 km) from coastal baselines, granting sovereign rights for economic exploration, fishing, and energy extraction under UNCLOS.\n` +
        `• **Sentinel Engine**: AUREXO computes geodesic distance to IMBL in real time using Turf.js polygons to prevent accidental border crossings.`
      );
    }
  }

  // 4. AIS Vessel Fleet Tracking
  if (data.vesselData) {
    const vd = data.vesselData;
    if (vd.matchedVessel) {
      const v = vd.matchedVessel;
      return (
        `**${v.name}** (${v.vesselType})\n\n` +
        `• **Current Coordinates**: ${v.coordinates.latitude.toFixed(2)}°N, ${v.coordinates.longitude.toFixed(2)}°E\n` +
        `• **Speed & Course**: ${v.speedKnots} knots at heading ${v.headingDegrees}°\n` +
        `• **Status / Mission**: ${v.status} — ${v.destination}\n` +
        `• **MMSI / ID**: ${v.mmsi}\n\n` +
        `Vessel telemetry is logged in the AUREXO AIS Fleet Registry.`
      );
    }
    if (vd.nearestVessel) {
      const nv = vd.nearestVessel;
      return (
        `**Nearest Active Vessel**: **${nv.vessel.name}**\n\n` +
        `• **Distance**: **${nv.distanceKm} km** from the target position\n` +
        `• **Type**: ${nv.vessel.vesselType} (MMSI: ${nv.vessel.mmsi})\n` +
        `• **Speed & Heading**: ${nv.vessel.speedKnots} knots at ${nv.vessel.headingDegrees}°\n` +
        `• **Destination**: ${nv.vessel.destination}`
      );
    }
  }

  // 5. Regional Warnings Scan
  if (Array.isArray(data.regionalWarnings)) {
    const rough = data.regionalWarnings.filter((r) => r.isSeaRough || r.activeWarningsCount > 0);
    if (rough.length === 0) {
      return (
        `**Regional Sea State Scan Complete**\n\n` +
        `All 9 Indian coastal sectors (Gujarat, Konkan, Malabar, Coromandel, Andhra, Odisha, Bengal, Lakshadweep, Andaman) currently report **normal, favorable sea states** with wave heights below 2.0m.\n\n` +
        `Safe for standard commercial navigation and coastal fishing operations.`
      );
    }
    const sectorLines = rough
      .map((r) => {
        const name = r.regionName ?? r.name ?? 'Sector';
        const wave = r.representativeObservation?.waveHeightMeters ?? r.observation?.wave?.heightMeters ?? '?';
        return `• **${name}**: Wave height ${wave}m — ${r.isSeaRough ? 'Elevated Rough Sea State' : 'Advisory Issued'}`;
      })
      .join('\n');

    return (
      `**Active Maritime Advisories Detected across Indian Sectors**:\n\n` +
      `${sectorLines}\n\n` +
      `Mariners and small craft operators in these sectors are advised to exercise heightened vigilance.`
    );
  }

  // 6. Marine Observation & Safety Directives
  const parts: string[] = [];

  if (data.conditions) {
    const c = data.conditions;
    parts.push(
      `**Current Marine Conditions for ${c.locationName ?? 'Indian Coastal Waters'}**:`
    );
    if (c.wave) {
      parts.push(
        `• **Sea State**: Wave height is **${c.wave.heightMeters !== undefined ? c.wave.heightMeters.toFixed(2) : '0.00'} m** (${c.wave.category ?? 'Normal'}) with a swell period of ${c.wave.periodSeconds !== undefined ? c.wave.periodSeconds.toFixed(1) : '0.0'} s.`
      );
    }
    if (c.wind) {
      parts.push(
        `• **Wind**: **${c.wind.speedKmh !== undefined ? c.wind.speedKmh.toFixed(1) : '0.0'} km/h** (${c.wind.beaufortDescription ?? 'Gentle'}, Beaufort force ${c.wind.beaufortScale ?? 2}) with gusts up to ${c.wind.gustsKmh !== undefined ? c.wind.gustsKmh.toFixed(1) : '0.0'} km/h.`
      );
    }
    if (c.seaSurfaceTemperatureCelsius !== undefined) {
      parts.push(
        `• **Sea Surface Temperature (SST)**: **${c.seaSurfaceTemperatureCelsius.toFixed(1)}°C**.`
      );
    }
    if (c.currents) {
      parts.push(
        `• **Ocean Currents**: Velocity of ${c.currents.velocityKmh !== undefined ? c.currents.velocityKmh.toFixed(1) : '0.0'} km/h at heading ${c.currents.directionDegrees ?? 0}°.`
      );
    }
    parts.push(
      `• **Safety Assessment**: ${c.isSafeForSmallCraft ? 'SAFE for small fishing craft and recreational vessels.' : 'CAUTION: Hazardous conditions for small craft.'} ${c.advisoryText ?? 'Maintain bridge watch.'}`
    );
  }

  if (data.geofence) {
    const g = data.geofence;
    parts.push(`\n**Geospatial & Boundary Sentinel**:`);
    parts.push(`• **Boundary Status**: **${g.riskStatus.toUpperCase()}**`);
    parts.push(`• **Distance to ${g.nearestNeighborCountry} IMBL**: **${g.distanceToIMBLKm} km**`);
    if (g.isInsideMarineProtectedArea) {
      parts.push(`• **Protected Zone Alert**: Located inside **${g.protectedAreaName}**. Commercial fishing and trawling prohibited under the Wildlife Protection Act.`);
    }
    parts.push(`• **Directives**: ${g.notes}`);
  }

  if (data.pfz) {
    const p = data.pfz;
    parts.push(`\n**Potential Fishing Zones (PFZ Guidelines)**:`);
    parts.push(`*${p.message}*`);
    p.zones.slice(0, 3).forEach((z, i) => {
      parts.push(
        `${i + 1}. **${z.name}** (~${z.distanceFromCoastKm} km offshore, depth: ${z.depthMeters}m). Target species: ${z.targetSpecies.join(', ')}. Chlorophyll indicator: ${z.chlorophyllStatus}.`
      );
    });
  }

  if (data.route) {
    const r = data.route;
    parts.push(`\n**Navigational Passage Corridor**:`);
    parts.push(`• Total Distance: **${r.totalDistanceKm} km** (~${r.estimatedTravelTimeHours} hours at 12 knots).`);
    parts.push(`• Corridor Risk: **${r.overallSafety}**.`);
    parts.push(`• Route Advisory: ${r.advisory}`);
  }

  if (parts.length === 0) {
    return `ORCA has received your inquiry. Please select a coastal point on the map or ask a tactical question regarding waves, weather, vessel tracking, or maritime boundaries.`;
  }

  return parts.join('\n');
}
